name: Docker Compose Test Run

on:
  pull_request:
    branches: [ main ]

jobs:
  docker_compose_interaction_test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Pull Docker Image
      run: docker pull benjisho/stock_advisor

    - name: Run Docker Compose with Expect
      run: |
        expect -c "
          set timeout 600
          spawn docker compose run --rm stock_advisor
          expect \"Enter the stock symbol (e.g., AAPL):\"
          send \"AAPL\r\"
          expect \"Successfully fetched\"
        "

    - name: Stop and Remove Docker Containers (Just in case)
      run: docker compose down

    - name: Remove Docker Image
      run: docker rmi benjisho/stock_advisor

    timeout-minutes: 10
