name: Python venv Test Run

on:
  pull_request:
    branches: [ main ]

jobs:
  python_venv_test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Set up Python Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt

    - name: Run Python Script with Expect
      run: |
        expect -c "
          set timeout 600
          spawn python3 main.py
          expect \"Enter the stock symbol (e.g., AAPL):\"
          send \"AAPL\r\"
          expect \"Successfully fetched\"
        "

    - name: Deactivate Python Environment and Clear venv Directory
      run: |
        source venv/bin/activate
        deactivate
        python3 -m venv --clear venv

      timeout-minutes: 10
